### ISSUE TITLE
(re)newcommand without brackets seems to be valid but brakes the parser

### ISSUE THREAD

**Issue by d-krupke** [d-krupke/flachtex#5]
Commands like `\renewcommand\thesubfigure{(\alph{subfigure})}` will throw an exception.
```
Traceback (most recent call last):
  File "/home/krupke/.local/bin/checkmytex", line 33, in <module>
    sys.exit(load_entry_point('CheckMyTex==0.8.0', 'console_scripts', 'checkmytex')())
  File "/home/krupke/.local/lib/python3.10/site-packages/checkmytex/__main__.py", line 29, in main
    latex_document = LatexDocument(args.path[0])
  File "/home/krupke/.local/lib/python3.10/site-packages/checkmytex/latex_document/latex_document.py", line 88, in __init__
    self._find_command_definitions(path, file_finder)
  File "/home/krupke/.local/lib/python3.10/site-packages/checkmytex/latex_document/latex_document.py", line 111, in _find_command_definitions
    for cmd in cmds:
  File "/home/krupke/.local/lib/python3.10/site-packages/flachtex/command_substitution.py", line 48, in find_new_commands
    for match in cf.find_all(str(latex_document)):
  File "/home/krupke/.local/lib/python3.10/site-packages/flachtex/command_finder.py", line 252, in find_all
    result = self.find(text, begin)
  File "/home/krupke/.local/lib/python3.10/site-packages/flachtex/command_finder.py", line 237, in find
    self._read_parameter(stream, "{", "}")  # skip definition name
  File "/home/krupke/.local/lib/python3.10/site-packages/flachtex/command_finder.py", line 200, in _read_parameter
    raise ValueError("Parameters without brackets.")
ValueError: Parameters without brackets.
```

**Comment by d-krupke** [comment]
This is extremely difficult to parse: We need to know the semantic to know that `\thesubfigure` is the first argument and `{...}` is the second argument belonging to `renewcommand` and not `\thesubfigure`.

**Comment by d-krupke** [comment]
added try-catch-clauses. This is not the optimal solution but better than failure.
